### ISSUE TITLE
Expo Snack en-gb IOS badge is not loading

### ISSUE THREAD

**Issue by jimmi-joensson** [usekeyhole/react-native-store-badges#2]
**Describe the bug**
The Expo Snack's en-gb IOS badge is not loading

**To Reproduce**
1. Go to [https://snack.expo.dev/@reinhardt/react-native-store-badges?](https://snack.expo.dev/@reinhardt/react-native-store-badges)

**Expected behavior**
That the IOS badge would load

**Screenshots**
![image](https://github.com/usekeyhole/react-native-store-badges/assets/15996198/a0a8383b-a0d9-4c69-ade5-2e889842536c)
![image](https://github.com/usekeyhole/react-native-store-badges/assets/15996198/d2373ba9-16ad-4195-ab5b-502378a614ec)

**Additional context**
Looks like it is primarily an issue with CORS policy.

Changing the locale to "en-US" fixed the issue and would probably be the best locale default anyway

![image](https://github.com/usekeyhole/react-native-store-badges/assets/15996198/4639d7e7-53c9-43f1-9f32-33b2b7a654d3)

**Comment by ReinhardtR** [comment]
The plugin default to the locale of the users system (if possible) or fallbacks to "en-US". Looks like your system is determined to be "en-gb"

To ensure this doesn't happen again the Expo Snack example now specifies "en-US" as the locale, by using the locale prop.
